platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/cosmos33/MMSpecs.git'

target 'TTTCosmosBeauty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TTTCosmosBeauty
  pod 'MMBeautyKit'
  pod 'MMCV', '1.1.0'

end
